# Generated by Django 4.2.3 on 2023-08-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descritption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tittle',
            field=models.CharField(max_length=200),
        ),
    ]
